import { t } from '../i18n/i18n';

const ocrTranslate = (code: string, fallback: string): string => {
  const key = `ocrLanguage.${code}`;
  const value = t(key);
  // 模块加载时 i18n 尚未初始化，t() 可能返回 undefined/空串，回退到英文名
  return value && value !== key ? value : fallback;
};

export const tesseractLanguages: Record<string, string> = {
  eng: ocrTranslate('eng', 'English'),
  afr: ocrTranslate('afr', 'Afrikaans'),
  amh: ocrTranslate('amh', 'Amharic'),
  ara: ocrTranslate('ara', 'Arabic'),
  asm: ocrTranslate('asm', 'Assamese'),
  aze: ocrTranslate('aze', 'Azerbaijani'),
  aze_cyrl: ocrTranslate('aze_cyrl', 'Azerbaijani - Cyrillic'),
  bel: ocrTranslate('bel', 'Belarusian'),
  ben: ocrTranslate('ben', 'Bengali'),
  bod: ocrTranslate('bod', 'Tibetan'),
  bos: ocrTranslate('bos', 'Bosnian'),
  bul: ocrTranslate('bul', 'Bulgarian'),
  cat: ocrTranslate('cat', 'Catalan; Valencian'),
  ceb: ocrTranslate('ceb', 'Cebuano'),
  ces: ocrTranslate('ces', 'Czech'),
  chi_sim: ocrTranslate('chi_sim', 'Chinese - Simplified'),
  chi_tra: ocrTranslate('chi_tra', 'Chinese - Traditional'),
  chr: ocrTranslate('chr', 'Cherokee'),
  cym: ocrTranslate('cym', 'Welsh'),
  dan: ocrTranslate('dan', 'Danish'),
  deu: ocrTranslate('deu', 'German'),
  dzo: ocrTranslate('dzo', 'Dzongkha'),
  ell: ocrTranslate('ell', 'Greek, Modern (1453-)'),
  enm: ocrTranslate('enm', 'English, Middle (1100-1500)'),
  epo: ocrTranslate('epo', 'Esperanto'),
  est: ocrTranslate('est', 'Estonian'),
  eus: ocrTranslate('eus', 'Basque'),
  fas: ocrTranslate('fas', 'Persian'),
  fin: ocrTranslate('fin', 'Finnish'),
  fra: ocrTranslate('fra', 'French'),
  frk: ocrTranslate('frk', 'German Fraktur'),
  frm: ocrTranslate('frm', 'French, Middle (ca. 1400-1600)'),
  gle: ocrTranslate('gle', 'Irish'),
  glg: ocrTranslate('glg', 'Galician'),
  grc: ocrTranslate('grc', 'Greek, Ancient (-1453)'),
  guj: ocrTranslate('guj', 'Gujarati'),
  hat: ocrTranslate('hat', 'Haitian; Haitian Creole'),
  heb: ocrTranslate('heb', 'Hebrew'),
  hin: ocrTranslate('hin', 'Hindi'),
  hrv: ocrTranslate('hrv', 'Croatian'),
  hun: ocrTranslate('hun', 'Hungarian'),
  iku: ocrTranslate('iku', 'Inuktitut'),
  ind: ocrTranslate('ind', 'Indonesian'),
  isl: ocrTranslate('isl', 'Icelandic'),
  ita: ocrTranslate('ita', 'Italian'),
  ita_old: ocrTranslate('ita_old', 'Italian - Old'),
  jav: ocrTranslate('jav', 'Javanese'),
  jpn: ocrTranslate('jpn', 'Japanese'),
  kan: ocrTranslate('kan', 'Kannada'),
  kat: ocrTranslate('kat', 'Georgian'),
  kat_old: ocrTranslate('kat_old', 'Georgian - Old'),
  kaz: ocrTranslate('kaz', 'Kazakh'),
  khm: ocrTranslate('khm', 'Central Khmer'),
  kir: ocrTranslate('kir', 'Kirghiz; Kyrgyz'),
  kor: ocrTranslate('kor', 'Korean'),
  kur: ocrTranslate('kur', 'Kurdish'),
  lao: ocrTranslate('lao', 'Lao'),
  lat: ocrTranslate('lat', 'Latin'),
  lav: ocrTranslate('lav', 'Latvian'),
  lit: ocrTranslate('lit', 'Lithuanian'),
  mal: ocrTranslate('mal', 'Malayalam'),
  mar: ocrTranslate('mar', 'Marathi'),
  mkd: ocrTranslate('mkd', 'Macedonian'),
  mlt: ocrTranslate('mlt', 'Maltese'),
  msa: ocrTranslate('msa', 'Malay'),
  mya: ocrTranslate('mya', 'Burmese'),
  nep: ocrTranslate('nep', 'Nepali'),
  nld: ocrTranslate('nld', 'Dutch; Flemish'),
  nor: ocrTranslate('nor', 'Norwegian'),
  ori: ocrTranslate('ori', 'Oriya'),
  pan: ocrTranslate('pan', 'Panjabi; Punjabi'),
  pol: ocrTranslate('pol', 'Polish'),
  por: ocrTranslate('por', 'Portuguese'),
  pus: ocrTranslate('pus', 'Pushto; Pashto'),
  ron: ocrTranslate('ron', 'Romanian; Moldavian; Moldovan'),
  rus: ocrTranslate('rus', 'Russian'),
  san: ocrTranslate('san', 'Sanskrit'),
  sin: ocrTranslate('sin', 'Sinhala; Sinhalese'),
  slk: ocrTranslate('slk', 'Slovak'),
  slv: ocrTranslate('slv', 'Slovenian'),
  spa: ocrTranslate('spa', 'Spanish; Castilian'),
  spa_old: ocrTranslate('spa_old', 'Spanish; Castilian - Old'),
  sqi: ocrTranslate('sqi', 'Albanian'),
  srp: ocrTranslate('srp', 'Serbian'),
  srp_latn: ocrTranslate('srp_latn', 'Serbian - Latin'),
  swa: ocrTranslate('swa', 'Swahili'),
  swe: ocrTranslate('swe', 'Swedish'),
  syr: ocrTranslate('syr', 'Syriac'),
  tam: ocrTranslate('tam', 'Tamil'),
  tel: ocrTranslate('tel', 'Telugu'),
  tgk: ocrTranslate('tgk', 'Tajik'),
  tgl: ocrTranslate('tgl', 'Tagalog'),
  tha: ocrTranslate('tha', 'Thai'),
  tir: ocrTranslate('tir', 'Tigrinya'),
  tur: ocrTranslate('tur', 'Turkish'),
  uig: ocrTranslate('uig', 'Uighur; Uyghur'),
  ukr: ocrTranslate('ukr', 'Ukrainian'),
  urd: ocrTranslate('urd', 'Urdu'),
  uzb: ocrTranslate('uzb', 'Uzbek'),
  uzb_cyrl: ocrTranslate('uzb_cyrl', 'Uzbek - Cyrillic'),
  vie: ocrTranslate('vie', 'Vietnamese'),
  yid: ocrTranslate('yid', 'Yiddish'),
};

/**
 * 惰性取语言的本地化显示名：在 i18n 初始化完成后调用，优先返回本地化名称；
 * 模块加载时 tesseractLanguages 只存了英文兜底名，此处每次调用都会重新走 t()。
 */
export const getTesseractLanguageName = (code: string): string => {
  const key = `ocrLanguage.${code}`;
  const value = t(key);
  return value && value !== key ? value : (tesseractLanguages[code] ?? code);
};
